spring:
  application:
    name: demo-server
  cloud:
    stream:
      function:
        definition: operationsProcessor
      bindings:
        operationsProcessor-in-0:
          destination: operationsInputQueue
        operationsProcessor-out-0:
          destination: operationsOutputQueue